export const GET = () => {
  const experienceData = [
    {
      id: '1',
      position: 'Senior Software Engineer / Radency',
      date: 'Feb. 2023 - Current',
      projectName: 'Project from scratch (USA)',
      responsibilities: 'project from scratch, architecture planning (front end), all technical solutions, creating tasks, development of new features, writing unit tests, code review, mentoring',
      technologies: 'TypeScript, React, Next.js, React Hook Form, JSX, Jest + React Testing Library, Material-UI, GraphQL/Apollo, TanStack Query (FKA React Query), Chart.js',
      tools: 'GitLab, WebStorm, GIT, Jira, Figma, Miro',
    },
    {
      id: '2',
      position: 'Senior Software Engineer (Web Solutions) / Infopulse',
      date: 'Feb. 2020 - Jan. 2023',
      projectName: 'Project 1',
      responsibilities: 'technical interviews, building a scalable web app and mobile app, developing new features, writing unit tests, code review, offering and implementing my own ideas for improving UX/UI, a support web application for different browsers, developing via TDD approach (Jest), building production bundles using Webpack',
      technologies: 'JavaScript/TypeScript, React, MobX, JSX, NodeJS, Webpack, Jest, Docker, React Native',
      tools: 'Azure DevOps, WebStorm, GIT, Jira, Xcode',
    },
    {
      id: '3',
      position: 'Front End Lead/Senior Software Engineer / Infopulse',
      date: 'Jul. 2021 - Sep. 2023',
      projectName: 'Incognito name (part-time)',
      responsibilities: 'front end team lead, mentoring, front end team planning, development of new features, code review, all Scrum activities, investigation, task assessment',
      technologies: 'JavaScript/TypeScript, React, Redux, Redux Form, JSX, Jest + React Testing Library, Material-UI, Highcharts',
      tools: 'Azure DevOps, WebStorm, GIT, Jira, Zeplin',
    },
    {
      id: '4',
      position: 'Senior Software Engineer/Front End Tech Lead / K2Fly (prev Sateva)',
      date: 'Jul. 2020 - Aug. 2021',
      projectName: 'Model Manager Solution',
      responsibilities: 'project from scratch, architecture planning (frontend), all technical solutions, development of new features, writing unit tests, code review, developing via TDD approach (Jest), mentoring',
      technologies: 'TypeScript, React, Redux, Redux-Saga, JSX, Webpack, Jest, Material-UI, react-awesome-query-builder',
      tools: 'WebStorm, GIT, Jira, Bitbucket, Everhour',
    },
    {
      id: '5',
      position: 'Senior Javascript Developer / Ciklum',
      date: 'Oct. 2018 - Feb. 2020',
      projectName: 'Proactima, Risk management',
      responsibilities: 'improving the performance of the application as a result of refactoring and code analysis, discussing user stories with the client, maintaining CI/CD process on VSTS, offering and implementing my own ideas for improving UX/UI, architecture planning, development of new features, UX/UI, writing unit tests, code review, a support web application for different browsers, developing via TDD approach (Jest), building production bundles using Webpack',
      technologies: 'JavaScript, React, React-Bootstrap, Redux, styled-components, JSX, NodeJS, Webpack, Jest',
      tools: 'Azure, Azure DevOps, WebStorm, Jira',
    },
    {
      id: '6',
      position: 'Middle Javascript Developer / GlobalLogic',
      date: 'Jul. 2017 – Oct. 2018',
      projectName: 'Avid Technology',
      responsibilities: 'Creating and supporting reusable components (ES, React, npm packages) for third-party developers, supporting/mentoring another team (Junior team), Developing backend services using NodeJS, developing new features, bugs fixing, refactoring code, writing unit tests, code review, building production bundles using Webpack, configuring nginx, maintaining CI/CD process on Gitlab, with Docker and Rpms',
      technologies: 'JavaScript, React, Redux, JSX, SCSS, JSON, NodeJS, GIT, Webpack',
      tools: 'IntelliJ IDEA, Jenkins, GitLab, Jira, Docker, Kubernetes',
    },
    {
      id: '7',
      position: 'Junior/Middle Javascript/C# Developer / Terrasoft',
      date: 'Dec. 2015 – Jul. 2017',
      projectName: 'CRM for marketing, sales, and service',
      responsibilities: 'participated in architecture planning of tasks, client support, development of new features, bugs fixing, refactoring code (was a lot of legacy code), writing unit tests and acceptance tests (Javascript and C#), code review, developing Front-End (MVVM, ExtJs, LESS, C#) part of the large-scale CRM system, maintaining CI process on TeamCity',
      technologies: 'JavaScript, ExtJS, RequireJS, BackboneJS, C#, .NET, MSSQL, Oracle, CSS, LESS, JSON, NodeJS',
      tools: 'WebStorm, Microsoft Visual Studio, SVN, JIRA',
    },
    {
      id: '8',
      position: 'Junior Frontend Developer / Modern Telecom Engineering',
      date: 'Jan. 2015 – Dec. 2015',
      projectName: 'Internal websites for LLC “MTE”',
      responsibilities: 'implementing responsive web design and entire front-end functionality, designing and developing SPA',
      technologies: 'Bootstrap 3, HTML5, CSS3, JavaScript, jQuery, PHP',
      tools: 'WebStorm',
    },
  ];

  return new Response(JSON.stringify(experienceData), {
    status: 200,
    headers: { 'Content-Type': 'application/json' },
  });
};
